### ISSUE TITLE
GitHub Action: Add a Greeting Action for new contributors

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/Rotten-Scripts-Web#4]
## Description

Add a GitHub Action to greet new contributors. 

Use these as a reference: 

- https://github.com/HarshCasper/Rotten-Scripts/blob/master/.github/workflows/greeting.yml
- https://github.com/HarshCasper/Rotten-Scripts/blob/master/.github/workflows/greetings.yml

Know more about GitHub Actions here: 

- https://docs.github.com/en/actions
- https://dev.to/github/what-are-github-actions-3pml
- https://medium.com/swlh/what-is-github-action-and-how-do-they-help-c8b254118fa5
- https://github.com/garg3133/welcome-new-contributors
- https://www.youtube.com/watch?v=gPW6b-EHSEA

**Comment by Sukriti-sood** [comment]
@HarshCasper  Will this [Welcome Bot](https://github.com/apps/welcome) works , this has also feature to comment on PR merge for first time contributors.

**Comment by Sukriti-sood** [comment]
@HarshCasper I have merged my pr but welcome bot still needs to be install
